// Generated by https://quicktype.io

export interface UserWatchedMovie {
	success: boolean;
	results: Result[];
}

export interface Result {
	media_id: string;
	media_type: MediaType;
	media_title: string;
	media_poster: string;
	user_rating: number;
	username: Username;
	avatar_url: string;
	media_release: null | string;
	media_rating: number | null;
	iswatchlisted: boolean;
	iswatched: boolean;
	isfavorited: boolean;
	isreviewd: boolean;
	iswriten: null | string;
	rating_by_app: string;
	created: string;
}

export enum MediaType {
	Movie = "movie",
	Tv = "tv",
}

export enum Username {
	Anshrathod = "Anshrathod",
}
